-- STRING FUNCTION
SELECT UPPER (NAME),AGE
FROM CUSTOMERS;

SELECT LOWER (NAME),AGE 
FROM CUSTOMERS;

SELECT UPPER (NAME),LENGTH(NAME) AS NAME_LENGHT 
FROM CUSTOMERS;

SELECT ID,NAME,SUBSTRING(NAME,3,3)
FROM CUSTOMERS;

SELECT ID,NAME,RIGHT(NAME,4)
FROM CUSTOMERS;

SELECT ID,NAME,LEFT(NAME,4)
FROM CUSTOMERS;

SELECT NAME,REPLACE(NAME ,'a','A') from customers;

SELECT ID ,NAME,CONCAT(LEFT(NAME,3),LEFT(ID::TEXT,3)) AS CODE FROM CUSTOMERS;

SELECT ID ,NAME,CONCAT_WS('-',LEFT(NAME,3),LEFT(ID::TEXT,3),DATE(ADMISSION)) AS CODE FROM CUSTOMERS;

SELECT * FROM CUSTOMERS;



